
INSERT INTO public.questions (question_text, category, life_stage, depth, good_for_photo, sort_order)
SELECT v.q, v.c, v.s, v.d, v.p, (row_number() OVER ())::int
FROM (VALUES
('What did your childhood bedroom look like?','Early Childhood','childhood','light',true),
('What toy did you carry everywhere with you?','Early Childhood','childhood','light',false),
('What did you usually eat for breakfast as a kid?','Early Childhood','childhood','light',false),
('Where did you play when the adults weren''t watching?','Early Childhood','childhood','light',false),
('What did your home sound like in the morning?','Early Childhood','childhood','light',false),
('What was your favorite place to hide as a child?','Early Childhood','childhood','light',false),
('What did you think was the scariest room in the house?','Early Childhood','childhood','light',false),
('Who taught you to ride a bike, and how did it go?','Early Childhood','childhood','light',false),
('What show did you rush home to watch?','Early Childhood','childhood','light',false),
('What did the inside of your grandparents'' house smell like?','Early Childhood','childhood','light',false),
('What was on the walls of your room?','Early Childhood','childhood','light',false),
('What game did you invent with the kids on your street?','Early Childhood','childhood','light',false),
('What did you get in trouble for most often?','Early Childhood','childhood','light',false),
('What was your favorite pair of shoes as a kid?','Early Childhood','childhood','light',false),
('What did you want to be when you grew up, at age six?','Early Childhood','childhood','light',false),
('Who made everyone laugh at family gatherings?','Family','childhood','light',false),
('What phrase did one of your parents repeat constantly?','Family','childhood','light',false),
('What meal reminds you most of your family?','Family','childhood','light',false),
('What family tradition seemed completely normal to you but unusual to others?','Family','childhood','light',false),
('Who in your family told the best stories?','Family','childhood','light',false),
('What food did your family always have at home when you were growing up?','Family','childhood','light',false),
('What did your family usually do on Sunday mornings when you were growing up?','Family','childhood','light',false),
('Who was the funniest person in your family growing up?','Family','childhood','light',false),
('What did your family do on weekends?','Family','childhood','light',false),
('Who did you look most like in your family, and who told you so?','Family','childhood','light',false),
('What did your mother keep in her purse?','Family','childhood','light',false),
('What did your father do for work, and what did you think it was?','Family','childhood','light',false),
('What was the family car, and what did it smell like inside?','Family','childhood','light',true),
('Who always showed up at the holidays without fail?','Family','childhood','light',false),
('What did your parents repeatedly tell you as a child?','Family','childhood','light',false),
('Who was the first teacher you clearly remember?','School','childhood','light',false),
('Where did you sit during lunch?','School','childhood','light',false),
('What subject came naturally to you?','School','childhood','light',false),
('What subject did you dread?','School','childhood','light',false),
('What trouble did you get into at school?','School','childhood','light',false),
('What did you carry your books in?','School','childhood','light',false),
('Who did you walk to school with?','School','childhood','light',false),
('What did the school cafeteria smell like?','School','childhood','light',false),
('What was written in your yearbook?','School','childhood','light',false),
('What school assembly or event do you still remember clearly?','School','childhood','light',false),
('Who was the class clown, and what did they do?','School','childhood','light',false),
('What did you do during recess?','School','childhood','light',false),
('Where did you usually go when you wanted to get out of the house as a teenager?','Teenage Years','teens','light',false),
('What music did you listen to constantly?','Teenage Years','teens','light',false),
('What did you think was cool that seems ridiculous now?','Teenage Years','teens','light',false),
('What did your friends usually do together?','Teenage Years','teens','light',false),
('What was the first party you remember?','Teenage Years','teens','light',false),
('What piece of clothing did you wear constantly?','Teenage Years','teens','light',true),
('Who was your first crush?','Teenage Years','teens','light',false),
('What did your bedroom walls look like at sixteen?','Teenage Years','teens','light',false),
('What did you and your friends talk about late at night?','Teenage Years','teens','light',false),
('What rule did you break that your parents never found out about?','Teenage Years','teens','light',false),
('Where did you hang out when you had nowhere to be?','Teenage Years','teens','light',false),
('What did you think your life would look like at thirty?','Teenage Years','teens','light',false),
('What was your first job?','Firsts','young_adult','light',false),
('What was your first car?','Firsts','young_adult','light',true),
('What''s the first thing you remember buying with money you earned yourself?','Firsts','young_adult','light',false),
('What was your first big trip without your family?','Firsts','young_adult','light',false),
('What was the first computer or game console you used?','Firsts','young_adult','light',false),
('What happened the first time you drove alone?','Firsts','young_adult','light',false),
('What was the first concert you went to?','Firsts','young_adult','light',false),
('What was your first apartment like?','Firsts','young_adult','light',false),
('What was the first meal you learned to cook?','Firsts','young_adult','light',false),
('What was the first thing you saved up for?','Firsts','young_adult','light',false),
('Who understood you particularly well growing up?','People','any','medium',false),
('Who taught you something you''ve never forgotten?','People','any','medium',false),
('Who intimidated you when you were young?','People','any','medium',false),
('Who made you laugh harder than anyone else?','People','any','medium',false),
('Who did you lose touch with but still think about?','People','any','deep',false),
('Who was your best friend when you were 10?','People','any','medium',false),
('Who changed the direction of your life?','People','any','deep',false),
('Who gave you advice you ignored at the time?','People','any','medium',false),
('Who was the most unusual person in your neighborhood?','People','any','medium',false),
('Who did you admire from a distance?','People','any','medium',false),
('What place from childhood can you still picture perfectly?','Places','any','light',false),
('Where did your family go for special occasions?','Places','any','light',false),
('What neighborhood did you know by heart?','Places','any','light',false),
('What place felt like freedom to you?','Places','any','light',false),
('What''s somewhere you wish you could visit exactly as it existed then?','Places','any','light',false),
('What did the walk to your front door look like?','Places','any','light',true),
('What store did you visit all the time that no longer exists?','Places','any','light',false),
('Where did you go to be alone?','Places','any','light',false),
('What''s the longest you''ve ever stayed in one home?','Places','any','light',false),
('What place did you move to that felt like starting over?','Places','any','light',false),
('What was your first day at your first real job like?','Work','adult','medium',false),
('Who was the best boss you ever had?','Work','adult','medium',false),
('What work mistake taught you the most?','Work','adult','medium',false),
('When did you first feel genuinely competent at something?','Work','adult','medium',false),
('What job did you think you''d have when you were a child?','Work','adult','medium',false),
('What did you wear to work at your first job?','Work','adult','light',true),
('Who did you eat lunch with at work?','Work','adult','light',false),
('What''s a job you took only for the money?','Work','adult','medium',false),
('What was the hardest work you''ve ever done with your hands?','Work','adult','medium',false),
('When did you know it was time to leave a job?','Work','adult','medium',false),
('What was always inside your refrigerator growing up?','Everyday Life','any','light',false),
('What did your family keep on top of the television?','Everyday Life','any','light',false),
('What did a normal Saturday look like when you were twelve?','Everyday Life','any','light',false),
('What phone did you first use regularly?','Everyday Life','any','light',false),
('What did people do before everyone had smartphones?','Everyday Life','any','light',false),
('What item in your home seemed incredibly modern at the time?','Everyday Life','any','light',false),
('What was considered expensive when you were growing up?','Everyday Life','any','light',false),
('What''s a smell that instantly takes you somewhere else?','Everyday Life','any','light',false),
('What sound do you not hear anymore?','Everyday Life','any','light',false),
('What did your family do when the power went out?','Everyday Life','any','light',false),
('What was kept in the kitchen drawer that never closed properly?','Everyday Life','any','light',false),
('How did you get around before you could drive?','Everyday Life','any','light',false),
('What did you do when you were bored, before the internet?','Everyday Life','any','light',false),
('What chore was always yours?','Everyday Life','any','light',false),
('What did you keep in your wallet that wasn''t money?','Everyday Life','any','light',false),
('What''s something your grandparents did that people rarely do anymore?','Culture','any','medium',false),
('What holiday did your family celebrate differently from everyone else?','Culture','any','medium',false),
('What language or words were spoken at home that you didn''t hear elsewhere?','Culture','any','medium',false),
('What food did you think every family ate when you were growing up?','Culture','any','light',false),
('What news event do you remember exactly where you were for?','Culture','any','medium',false),
('What did people dress like when you were twenty?','Culture','any','light',false),
('What did your neighborhood do together that neighborhoods rarely do now?','Culture','any','medium',false),
('What advice have you given more than once?','Lessons','adult','medium',false),
('What did you believe strongly at twenty-five that you no longer believe?','Lessons','adult','deep',false),
('What''s something you were wrong about, and how did you find out?','Lessons','adult','deep',false),
('What''s a small decision that changed a lot?','Lessons','adult','deep',false),
('What do you know how to do that fewer people know how to do now?','Lessons','adult','medium',false)
) AS v(q,c,s,d,p);
